language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "sudo apt-get install libhdf4-dev"
# command to run tests
script:
  - ./runexamples.sh
  - nosetests -v
notifications:
  email:
    recipients:
      - fshahriar@gmail.com
    on_success: never
    on_failure: change
